name: API Tests

on:
  push:
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install flask pytest

      - name: Run API tests
        run: pytest -v
